language: node_js
node_js:
  - "10"

cache: yarn

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
